name: "Test in a Raku container"
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    container:
      image: ghcr.io/jj/raku-zef-gha
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: ${{ env.COMMITS }}
      - name: Install modules
        run: zef install --deps-only .
      - name: Test
        run: zef --debug test .



