name: "Test"
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run test
        run: docker run -t -v ${GITHUB_WORKSPACE}:/test jjmerelo/raku-test



