name: "Test in a Raku container - template"
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    container:
      image: ghcr.io/jj/raku-zef-gha
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache installed dists
        uses: actions/cache@v2
        id: meta6
        with:
          path: ~/.raku/precomp
          key: ${{ runner.os }}-${{ hashFiles('META6.json') }}
      - name: Show stuff
        run: ls -a /__w/raku-dist-template/raku-dist-template
      - name: Install modules
        if: steps.meta6.outputs.cache-hit != 'true'
        run: zef install --deps-only .
      - name: Test
        run: zef --debug test .



